"""agregar_descripcion_detallada

Revision ID: 4d3d9afadea5
Revises: 6463abe82341
Create Date: 2026-08-23 17:05:57.632201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d3d9afadea5'
down_revision: Union[str, Sequence[str], None] = '6463abe82341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patrimonio', sa.Column('descripcion_detallada', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patrimonio', 'descripcion_detallada')
    # ### end Alembic commands ###
