"""agregar_tabla_chat_contactos

Revision ID: 6463abe82341
Revises: 
Create Date: 2026-08-22 00:12:12.525816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6463abe82341'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_contactos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitante_id', sa.Integer(), nullable=True),
    sa.Column('receptor_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_contactos_id'), 'chat_contactos', ['id'], unique=False)
    op.create_index(op.f('ix_chat_contactos_receptor_id'), 'chat_contactos', ['receptor_id'], unique=False)
    op.create_index(op.f('ix_chat_contactos_solicitante_id'), 'chat_contactos', ['solicitante_id'], unique=False)
    op.drop_constraint(op.f('equipos_nro_inventario_key'), 'equipos', type_='unique')
    op.drop_index(op.f('ix_equipos_nro_inventario'), table_name='equipos')
    op.create_index(op.f('ix_equipos_nro_inventario'), 'equipos', ['nro_inventario'], unique=True)
    op.create_index(op.f('ix_equipos_id'), 'equipos', ['id'], unique=False)
    op.create_index(op.f('ix_mapas_celdas_id'), 'mapas_celdas', ['id'], unique=False)
    op.create_index(op.f('ix_mapas_grid_id'), 'mapas_grid', ['id'], unique=False)
    op.alter_column('mensajes_chat', 'remitente_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mensajes_chat', 'destinatario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('mensajes_chat_destinatario_id_fkey'), 'mensajes_chat', type_='foreignkey')
    op.drop_constraint(op.f('mensajes_chat_remitente_id_fkey'), 'mensajes_chat', type_='foreignkey')
    op.create_foreign_key(None, 'mensajes_chat', 'usuarios', ['destinatario_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'mensajes_chat', 'usuarios', ['remitente_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('sectores_nombre_key'), 'sectores', type_='unique')
    op.create_index(op.f('ix_sectores_id'), 'sectores', ['id'], unique=False)
    op.create_index(op.f('ix_sectores_nombre'), 'sectores', ['nombre'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sectores_nombre'), table_name='sectores')
    op.drop_index(op.f('ix_sectores_id'), table_name='sectores')
    op.create_unique_constraint(op.f('sectores_nombre_key'), 'sectores', ['nombre'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'mensajes_chat', type_='foreignkey')
    op.drop_constraint(None, 'mensajes_chat', type_='foreignkey')
    op.create_foreign_key(op.f('mensajes_chat_remitente_id_fkey'), 'mensajes_chat', 'usuarios', ['remitente_id'], ['id'])
    op.create_foreign_key(op.f('mensajes_chat_destinatario_id_fkey'), 'mensajes_chat', 'usuarios', ['destinatario_id'], ['id'])
    op.alter_column('mensajes_chat', 'destinatario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mensajes_chat', 'remitente_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_mapas_grid_id'), table_name='mapas_grid')
    op.drop_index(op.f('ix_mapas_celdas_id'), table_name='mapas_celdas')
    op.drop_index(op.f('ix_equipos_id'), table_name='equipos')
    op.drop_index(op.f('ix_equipos_nro_inventario'), table_name='equipos')
    op.create_index(op.f('ix_equipos_nro_inventario'), 'equipos', ['nro_inventario'], unique=False)
    op.create_unique_constraint(op.f('equipos_nro_inventario_key'), 'equipos', ['nro_inventario'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_chat_contactos_solicitante_id'), table_name='chat_contactos')
    op.drop_index(op.f('ix_chat_contactos_receptor_id'), table_name='chat_contactos')
    op.drop_index(op.f('ix_chat_contactos_id'), table_name='chat_contactos')
    op.drop_table('chat_contactos')
    # ### end Alembic commands ###
