"""agregar_usuario_id_a_patrimonio

Revision ID: fcbf251ce270
Revises: 4d3d9afadea5
Create Date: 2026-08-27 03:07:45.044197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcbf251ce270'
down_revision: Union[str, Sequence[str], None] = '4d3d9afadea5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patrimonio', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'patrimonio', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patrimonio', type_='foreignkey')
    op.drop_column('patrimonio', 'usuario_id')
    # ### end Alembic commands ###
